#!/bin/bash
# hjs
# 2019.12.02
NGINX=/usr/local/nginx/sbin/nginx
NGINX_START_SHELL='/usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf'
PID=/usr/local/nginx/logs/nginx.pid


start()
{
	if [ -f $PID ];then
		echo "nginx已经启动!"
	else
		#$NGINX
		echo "${NGINX_START_SHELL}"|bash
		echo "nginx启动成功!"
	fi
}

stop()
{
	if [ -f $PID ];then
		kill -15 `cat ${PID}`
		echo "nginx已经关闭!"
	else
		echo "nginx未启动!"
	fi
}

restart()
{	
	if [ -f $PID ];then
		stop
	fi
	start
}

status()
{
        if [ $(ps aux |grep -Ei "nginx"|grep -Ei "master"|grep -v grep|wc -l) -ge 1 ];then
                echo "nginx is active"
	else
		exit 1
        fi
}

reload()
{
        if [ -f $PID ]
        then
                kill -1 `cat $PID`
		if [ $? -eq 0 ];then
			echo "nginx reload succful"
		else
			echo "nginx reload fail"
		fi
        fi
}



case $1 in

"start") 
	start
	;;

"stop") 
	stop
	;;

"restart") 
	restart
	;;

"status") 
	status
        ;;

"reload") 
	reload
        ;;


*) echo "请输入正确的操作参数 start|stop|restart|status|reload"
	;;
esac
